/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.util.ArrayList;
import mediateca.Articulo;
import mediateca.*;

/**
 *
 * @author Adrian
 */
public class VerArticulo extends javax.swing.JFrame {

    /**
     * Creates new form VerArticulo
     */
    Articulo a;
    Usuario u = Fachada.getInstancia().mediateca.usuarioConectado;
    boolean observar;
    public VerArticulo(int id) {
        initComponents();

        Inicializar(id);
    }

    private VerArticulo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void Inicializar(int id){
        this.a = Fachada.getInstancia().cargaArticulo(id);
        txtTitulo.setText(a.getTitulo());
        txtGenero.setText(a.getGenero());
        txtAutor.setText(a.getAutor());
        lblString.setVisible(false);
        txtString.setVisible(false);
        lblInt.setVisible(false);
        txtInt.setVisible(false);
        lblSinopsis.setVisible(false);
        txtSinopsis.setVisible(false);
        
        /*if(tipo.equals("AUDIO")){
            
            txtString.setVisible(false);
            lblString.setVisible(false);
            lblSinopsis.setVisible(false);
            txtSinopsis.setVisible(false);
            lblInt.setText("Duracion:");
            txtInt.setText(((Disco)arr.get(0)).getDuracion()+"");
        }
        if(tipo.equals("CINE")){
            Pelicula p = (Pelicula)a;
            txtString.setText(p.getActores());
            lblString.setText("Actores:");
            txtSinopsis.setText(p.getSinopsis());
            lblInt.setText("Duracion:");
            txtInt.setText(p.getDuracion()+"");
        }*/
        comprobarReserva();
        comprobarObservar();
    }
    public void comprobarReserva(){
        boolean reservar = true;
        if(Fachada.getInstancia().articuloUsuario(u.getId())!=null){
            reservar = false;
        }
        if(a.isReservado()||(!reservar)){
            btnReservar.setVisible(false);
            lblInf1.setText("Este articulo esta reservado");
        }else{
            btnReservar.setVisible(true);
            lblInf1.setText("Este articulo esta disponible");
        }
    }
    
    public void comprobarObservar(){
        observar = Fachada.getInstancia().estaObservando(a.getId(), u.getId());
        if(observar){
            btnObservar.setText("Dejar de observar");
            lblInf2.setText("Estas observando este articulo");
        }else{
            btnObservar.setText("Observar");
            lblInf2.setText("No observas este articulo");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        lblTitulo = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblInt = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        lblString = new javax.swing.JLabel();
        lblSinopsis = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSinopsis = new javax.swing.JTextArea();
        txtInt = new javax.swing.JTextField();
        txtString = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        lblInf1 = new javax.swing.JLabel();
        lblInf2 = new javax.swing.JLabel();
        btnReservar = new javax.swing.JButton();
        btnObservar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTitulo.setText("Titulo:");
        lblTitulo.setToolTipText("Titulo de la obra");

        lblGenero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblGenero.setText("Genero:");
        lblGenero.setToolTipText("Titulo de la obra");

        lblInt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblInt.setText("Paginas:");
        lblInt.setToolTipText("Titulo de la obra");

        lblAutor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAutor.setText("Autor:");
        lblAutor.setToolTipText("Titulo de la obra");

        lblString.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblString.setText("Ilustrador:");
        lblString.setToolTipText("Titulo de la obra");

        lblSinopsis.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSinopsis.setText("Sinopsis:");
        lblSinopsis.setToolTipText("Titulo de la obra");

        txtSinopsis.setEditable(false);
        txtSinopsis.setColumns(20);
        txtSinopsis.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtSinopsis.setRows(5);
        jScrollPane1.setViewportView(txtSinopsis);

        txtInt.setEditable(false);
        txtInt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtString.setEditable(false);
        txtString.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtGenero.setEditable(false);
        txtGenero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtTitulo.setEditable(false);
        txtTitulo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtAutor.setEditable(false);
        txtAutor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblInf1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblInf1.setText("Sinopsis:");
        lblInf1.setToolTipText("Titulo de la obra");

        lblInf2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblInf2.setText("Sinopsis:");
        lblInf2.setToolTipText("Titulo de la obra");

        btnReservar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnReservar.setText("Reservar");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        btnObservar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnObservar.setText("Observar");
        btnObservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObservarActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblString, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblInt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInt)
                            .addComponent(txtString, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtGenero, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAutor, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSinopsis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnReservar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(lblInf1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblInf2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnObservar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutor)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenero)
                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInt)
                    .addComponent(txtInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblString)
                    .addComponent(txtString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSinopsis)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInf2)
                    .addComponent(lblInf1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservar)
                    .addComponent(btnObservar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        // TODO add your handling code here:
        Fachada.getInstancia().reservarArticulo(a.getId(),u.getId());
        Inicializar(a.getId());
    }//GEN-LAST:event_btnReservarActionPerformed

    private void btnObservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObservarActionPerformed
        // TODO add your handling code here:
        if(observar){
            Fachada.noObservarArticulo(a.getId(), u.getId());
        }else{
            Fachada.observarArticulo(a.getId(), u.getId());
        }
        Inicializar(a.getId());
    }//GEN-LAST:event_btnObservarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        new BusquedaArticulos().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerArticulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObservar;
    private javax.swing.JButton btnReservar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblInf1;
    private javax.swing.JLabel lblInf2;
    private javax.swing.JLabel lblInt;
    private javax.swing.JLabel lblSinopsis;
    private javax.swing.JLabel lblString;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtInt;
    private javax.swing.JTextArea txtSinopsis;
    private javax.swing.JTextField txtString;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
